version: "3"
services:
  api:
    container_name: backend
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    env_file:
         - ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    container_name: db-postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: